provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  faas-template-r-fn:
    lang: dockerfile
    handler: ./faas-template-r-fn
    image: disarm/faas-template-r-fn:0.1.1
    environment:
      exec_timeout: 60
      write_timeout: 70
      read_timeout: 70
      combine_output: false
      # write_debug: true
