provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-ppmify:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-ppmify:0.2.0
    environment:
      exec_timeout: 600
      write_timeout: 700
      read_timeout: 700
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
